# Uncomment the next line to define a global platform for your project
platform :ios, '12.4.1'

target 'htn-Master' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SwiftSocket'
  # Pods for htn-Master

  target 'htn-MasterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'htn-MasterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
